### ISSUE TITLE
能否加入一个获取声调的函数或者支持声调输出格式

### ISSUE THREAD

**Issue by KumoKyaku** [toolgood/ToolGood.Words.Pinyin#5]
比如 "阿尔萨斯" 输出 "1341" 或者 "a1er3sa4si1".
现在输出"AĚrSàSī",无法取得每个字的声调.有一些声调相关的需求.

现有拼音类库中这个库是实现最好的,所以想在这个类库上继续发展.

**Comment by KumoKyaku** [comment]
采用数字1、2、3、4、5，代替《汉语拼音方案》中声调阴平（ˉ），阳平（ˊ），上声（ˇ），去声（ˋ），轻声（不标调）这几个标调符号。
https://baike.baidu.com/item/%E6%8B%BC%E9%9F%B3%E5%A3%B0%E8%B0%83/3031925

**Comment by toolgood** [comment]
有一些字是双拼音的。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toolgood/ToolGood.Words.Pinyin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 上午10:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[toolgood/ToolGood.Words.Pinyin] 能否加入一个获取声调的函数或者支持声调输出格式 (#5)





 
比如 "阿尔萨斯" 输出 "1341" 或者 "a1er3sa4si1".
 现在输出"AĚrSàSī",无法取得每个字的声调.有一些声调相关的需求.
 
现有拼音类库中这个库是实现最好的,所以想在这个类库上继续发展.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KumoKyaku** [comment]
把现有声调输出格式改成数字格式就可以了，我测了现有词库准确率很高了 ，现在拼音的声调输出格式，没办法拿到是几声

**Comment by KumoKyaku** [comment]
写了个低性能实现
https://github.com/0x3f3f3f3f/IsekaiNameGenerator/blob/main/Megumin.IsekaiNameGenerator/ToneHelper.cs
